name: Copy Data and Deploy Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '_data/faq_the_spoon.yml'

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy YAML to site/_data
        run: |
          mkdir -p docs/_data
          cp data/rag/faq_the_spoon.yml docs/_data/

  deploy:
    needs: copy-files
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
